global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app-blue"
    static_configs:
      - targets: ["app-blue:8080"]
    metrics_path: /health/metrics

  - job_name: "app-green"
    static_configs:
      - targets: ["app-green:8080"]
    metrics_path: /health/metrics

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
